### ISSUE TITLE
Remove assertion regarding tile levels that crashes the nc process

### ISSUE THREAD

**Issue by laurolins** [laurolins/nanocube#26]
Avoid crashing the server on this assertion:

Assertion failed: (min_address.level == max_address.level && min_address.x <= max_address.x && min_address.y <= max_address.y), function visitRange, file ../../src/QuadTree.hh, line 1146.

**Comment by vmarcinko** [comment]
Is there some quick workaround for this? I'm stumbling on this whenever I start playing with queries and enter some invalid tile data....

**Comment by laurolins** [comment]
Fixed in release 3.2
