### ISSUE TITLE
nanocube pseudocode obscurities

### ISSUE THREAD

**Issue by Pyroluk** [laurolins/nanocube#31]
Hello,

I am trying to comprehend the algorithm to build a nanocube. My final goal is to multithread the building process.
To understand the pseudocode which comes with the nanocube paper, I tried to apply it to the illustration on page 2 (Fig. 2).
Adding the first point (o1) works fine and I get the exact same result as illustrated. If I try to add the second point (o2) I run into the following problem:
Starting from the nanocube #1 in Fig. 2, we want to add the second point o2 ((0,1), (01,10) ; IPhone). According to the pseudocode on page 3 (Fig. 3), the following instructions will be performed in this order:
updated_nodes = empty set
ADD(nano_cube, o2, 1, S, ltime, updated_nodes)
[l1, l2] = CHAIN(S, 1)
stack = TRAILPROPERPATH(nano_cube, [l1(o2), l2(o2)])
		stack = STACK()
		PUSH(stack, nano_cube)
		node = nano_cube
		child = CHILD(nano_cube, (0,1))
		PUSH(stack, (0,1))
		node = (0,1)
		child = CHILD((0,1), (01,10))
		PUSH(stack, (01,10))
		node = (01,10)
		return stack
	child = null
	node = POP(stack) // (01,10)
	update = false
	update = true // Content is proper
	ADD(catNode, o2, 2, updated_nodes) // catNode is the node under (01,10)
		[ld] = CHAIN(S, 2)  //ld is the device labeling function
		stack = TRAILPROPERPATH(catNode, [ld(o2)])
			stack = STACK()
			PUSH(stack, catNode)
			node = catNode
			child = CHILD(catNode, “IPhone”)
			child = NEWPROPERCHILD(catNode, “IPhone”, NODE())
			PUSH(stack, “IPhone”)
			node = child
			return stack
		child = null
		node = POP(stack) // “IPhone” node
		update = false
		SETPROPERCONTENT(“IPhone”, SUMMEDTABLETIMESERIES()) //IPhoneTimeSeries
		update = true
		INSERT(IPhoneTimeSeries, ltime(o2))
		INSERT(updated_nodes, IPhoneTimeSeries)
		child = “IPhone” // IPhone Node
		node = POP(stack) // catNode
		update = false
		### Weirdness begins here ### Content of catNode is shared and not in updated_nodes
		shallowCopy = SHALLOWCOPY(androidTimeSeries) //CONTENT(catNode) is the Android Timeseries, isn’t it?
			node_sc = NODE()
			SETSHAREDCONTENT(node_sc, CONTENT(androidTimeSeries)) //what is the value of the second argument in this case? What is the content of a timeseries?

Did I do something wrong?

**Comment by laurolins** [comment]
You are right, Pyroluk. There is a problem there. ShallowCopy as written in the pseudo-code only works for internal nodes, not for time series. Line 14 should be something like

14: SetProperContent(node, d=dim(S) ? CopySummedTableTimeSeries(Content(node)) : ShallowCopy(Content(node)) )

Here is a video of the construction of the paper's example that gives us some intuition on the construction of that example:

https://www.dropbox.com/s/tinatdj3wg364n1/paper-example.mov?dl=0

Thanks for catch the problem there.

**Comment by Pyroluk** [comment]
Hi laurolins,

Thank you very much for the video. That helps a lot!
What does the green and orange color indicate while traversing the tree?

Could you provide me the name of the program used in this video and maybe even the code to simulate a nanocube?
This looks like the perfect tool to figure out a decent multithreaded insertion algorithm or an algorithm to merge pairs of partial nanocubes, as you mentioned in the "parallelizing the build process" thread.

Thanks again!
