### ISSUE TITLE
Compilation failure on Ubuntu 16.04 (nanocube3.3)

### ISSUE THREAD

**Issue by lsq210** [laurolins/nanocube#74]
I get the following issue when compiling the nanocubes3.3 on Ubuntu 16.04.  Any assistance appreciated!
I run the following commands:
````
sudo apt-get install build-essential
sudo apt-get install zlib1g-dev
sudo apt-get install libboost-all-dev
sudo apt-get install libcurl4-openssl-dev
````

```
wget https://github.com/laurolins/nanocube/archive/3.3.zip
unzip 3.3.zip
cd nanocube-3.3
./configure --prefix=$(pwd) 
make
```

After running `make` I got this error:
```
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --prefix=/home/luoshiqi/nanocubes --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
...
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing dlopen... -ldl
checking for dlerror... yes
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dld_link in -ldld... no
./configure: line 16476: syntax error near unexpected token `noext,mandatory'
./configure: line 16476: `AX_CXX_COMPILE_STDCXX_11(noext,mandatory)'
Makefile:393: recipe for target 'config.status' failed
make: *** [config.status] Error 2
```

**Comment by salivian** [comment]
For 16.04 and 3.3

Please install gcc 4.8 for c++11 support

https://packages.ubuntu.com/xenial/gcc-4.8

export CXX=g++-4.8 before running configure.

**Comment by lsq210** [comment]
> If you can ... please try the master or newer release, compiler support is much simpler.
> 
> For 16.04 and 3.3
> 
> Please install gcc 4.8 for c++11 support
> 
> https://packages.ubuntu.com/xenial/gcc-4.8
> 
> export CXX=g++-4.8 before running configure.

Thank you!  I installed gcc 4.8 but it still had the same problem😭
I tried nanocube4 in Ubuntu18.04, it works.

**Comment by salivian** [comment]
Glad that it works for you, the new version should be a lot more efficient.

Thanks!

Horace
